version: '3.2'
volumes:
  psql-data:

services:
  transponder:
    container_name: transponder
    image: webhookrelay/transponder:latest
    command:
      - /bin/transponder
      - --status-server
      - --api-server
    volumes:
      - type: bind # self-signed certs
        source: ./certs
        target: /certs
      - type: bind # accelerator database
        source: ./data
        target: /data
    ports:
      - 9300:9300
      - 9800:9800
      - 9801:9801
      - 9802:9802
      - 9803:9803
    healthcheck:
      test: curl --fail --insecure -s https://127.0.0.1:9803/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always  
    environment:
      # Authentication
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_API_KEY=${ADMIN_API_KEY}
      - ADMIN_API_SECRET=${ADMIN_API_SECRET}
      # Licensing
      - LICENSE=${LICENSE}
      # Webhook forwarding
      - PUBLIC_URL=${PUBLIC_URL}
      - LOGS_RETENTION_DAYS=${LOGS_RETENTION_DAYS}
      - LOGS_RETENTION_JOB_SCHEDULE=${LOGS_RETENTION_JOB_SCHEDULE}
      - ACCELERATOR_ENABLED=true
      - ACCELERATOR_BATCH_SIZE=500 # max size
      - XDG_DATA_HOME=/data
      # Connectivity
      - TUNNEL_API_PORT=9800
      - TUNNEL_HTTP_PORT=9801
      - TUNNEL_HTTPS_PORT=9802
      - MY_ADDRESS=${MY_ADDRESS}     
      # TLS
      - CERT_PATH=${CERT_PATH}
      - CERT_KEY_PATH=${CERT_KEY_PATH}
      # Misc
      - STATUS_PORT=9803
      - STATUS_USERNAME=${STATUS_USERNAME}
      - STATUS_PASSWORD=${STATUS_PASSWORD}
      - POSTGRES_HOST=psql
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=pgdb-transponder
  psql:
    image: postgres:11
    container_name: postgres
    restart: always
    volumes:
      - "psql-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=pgdb-transponder
      - PGDATA=/var/lib/postgresql/data/pgdata