version: '3.2'
services:
  transponder:
    container_name: transponder
    image: webhookrelay/transponder:0.8.3
    command:
      - /bin/transponder
      - --status-server
      - --api-server
    volumes:
      - type: bind # certs, data
        source: ./data
        target: /data
      - type: bind # certs, data
        source: ./certs
        target: /certs
    ports:
      - ${HTTPS_API_PORT}:${HTTPS_API_PORT} # API HTTPS port
      - ${HTTP_API_PORT}:${HTTP_API_PORT} # API HTTP port
      - 9302:9302 # GRPC port
      - 9800:9800 # Tunnel API port
      - 9801:9801 # Tunnel HTTP port
      - 9802:9802 # Tunnel HTTPS port
      - 9803:9803 # Status port
    restart: always
    env_file:
      - .env
    environment:
      # Certificate storage
      - XDG_DATA_HOME=/data
      # Tunnelling
      - TUNNEL_API_PORT=9800
      - TUNNEL_HTTP_PORT=9801
      - TUNNEL_HTTPS_PORT=9802